### PR TITLE
fix test script #165

### PR DESCRIPTION
**Pull request by jiro4989**
## Overview

- Version up 'setup-nim-action'
- Skip test on 'macOS' VM because devel-compiler doesn't exist
- Remove compiler-message from 'test/ref'
- Change test script

## Change test script

The current test script writes '--help' message and compiler message to 'test/out'.
It is difficult to ignore with 'grep'.
So I split 'compile' phase and 'run' command phase.

### CODE REVIEW

**Comment by jiro4989** [comment]
wait, I write description of this PR.

**Comment by jiro4989** [comment]
I wrote description of PR.

**Comment by jiro4989** [comment]
fmm, 'gh-pages' test failed.

**Comment by c-blake** [comment]
It is good to keep those compiler messages in test/ref (or test/out) for when I change something or Nim changes something to produce new warnings/errors.  I'm not sure why the debian thing is spitting out "....." lines, but we could probably filter those out, too, like the `grep -v '^CC'`.

I'm not sure why I cannot silence that observable stores the ways I was trying.  Silencing breaks for me locally, too, but works fine if I do an `@if nimHasWarningObservable..` in my `$HOME/.config/nim.cfg` (that `@if` is actually used by compiler `nim.cfg`'s, too).

**Comment by jiro4989** [comment]
fmm... I understood.

**Comment by c-blake** [comment]
I merged this but then still had to fix some stuff to get it working.  Basically, I had some things in my `nim.cfg` altering my output slightly. Now they are on the cmd line in `test.sh`.  (I never really tried to match other-environment-build with my-environment-build before your CI stuff.)

TBH, I spent most of the time on this trying to get code-local warning deactivation of `[ObservableStores]` working.  It still does not and I still don't know why. :(

**Pull request merged**
