### PR TITLE
Modernized nimble file to NimScript format (fixes warning), fixed nim…

### PR DESCRIPTION
**Pull request by SSPkrolik**
… compiler dep version (0.13.0) in devel branch, also caused installation issues on Windows

### CODE REVIEW

**Comment by c-blake** [comment]
Merged.  Thanks.  Say, if you are on Windows then maybe you could test if terminalWidth() works correctly.  I wrote code for it, but have never tried to even compile it.  I don't have a Win devel environment setup.

**Comment by SSPkrolik** [comment]
@c-blake actually try to figure out why not :)

c:\users\krolik\.nimble\pkgs\cligen-0.9.3\termwidth.nim(35, 9) Error: undeclared
 identifier: 'terminalWidthLowLevel'
Traceback (most recent call last)
nimble.nim(962)          nimble
nimble.nim(894)          doAction
nimble.nim(521)          install
nimble.nim(373)          installFromDir
nimble.nim(321)          buildFromDir
Error: unhandled exception: Build failed for package: rod [BuildFailed]

**Comment by SSPkrolik** [comment]
@c-blake seems like ...LowLevel is just misspelled, as it's an overloaded proc ...

**Comment by c-blake** [comment]
Yeah.  I saw that and pushed something as you were typing.  May still not compile. :)  Let me know.

**Comment by SSPkrolik** [comment]
@c-blake, Nah, it compiles perfectly :)

**Comment by c-blake** [comment]
Great.  It would be _awesome_ if you could test if it works (i.e., reports the right terminal width for a couple sizes of terminal)!  Probably just seeing if ``nim c -r test/SemiAutoMulti`` actually word wraps correctly would be the end-to-end test there.

**Comment by SSPkrolik** [comment]
@c-blake Already done, at least SemiAutoMulti seems to wrap words just fine.

**Comment by c-blake** [comment]
Fabulous.  Many thanks, Rostyslav.  Nice to resolve some Windows deployment uncertainty.  Let me know if you run into any other trouble.

**Comment by SSPkrolik** [comment]
@c-blake Sure. Thanks for developing awesome lib )))

**Comment by c-blake** [comment]
You're welcome.  I like it.  Glad to hear you do, too.  In several ways it can already do more than the Python 'argh' that inspired it, thanks partly to Nim's stronger static typing.  It sure seems a lot less work to use/learn than commandeer, docopt, etc., at least to me, but I know I'm biased. :)

**Pull request merged**
