### PR TITLE
Fix 88

### PR DESCRIPTION
**Pull request by pb-cdunn**
Background here: https://github.com/jangko/msgpack4nim/issues/30

Also note araq's comment here: https://forum.nim-lang.org/t/4681#29195 
But I don't think that problem is related.

### CODE REVIEW

**Comment by pb-cdunn** [comment]
I see your fix here: https://github.com/c-blake/cligen/commit/9c2d41955b63be7a9802aad4381a374fc6859638

Trying that  instead now ...

**Comment by pb-cdunn** [comment]
(This was a fix for #88.)

**Comment by c-blake** [comment]
For what it's worth, at least according to the docs for module search paths, that `"./"` is not syntactically necessary, though it may represent useful meaning to a human reader of the code emphasizing locality of the module.  I don't set up symlinks like you, though, and it's possible there are bugs.  So, let me know if it breaks without the `"./"`.

**Comment by pb-cdunn** [comment]
Could you link the docs on search-path? I was looking for that but didn't find it.

**Comment by c-blake** [comment]
Well, it's in `doc/nimc.rst` in the distribution.  In-file-search for "Search path handling" to get to the section.

**Comment by c-blake** [comment]
I agree that the "Collective imports from a directory" section in the manual that gets HTML-ified could use a few sentences about this (or maybe a new section just before it?). I find it hard to imagine that Araq would reject such a PR if you sent one, though you may have to iterate on the exact language.  Also, I think it's possible to `import` out of band from the `.nim` codebase from within `nim.cfg` (and probably `config.nims`).  `tests/import_in_config` and `tests/modules` show that, but I doubt it's documented anywhere.  Also, I believe the search path for `include` works just like `import` but that may not be mentioned anywhere, exactly.  Also, I wouldn't be shocked if there was some `pragma` that could update the search path in Nim code, but I don't know of one specifically.  You could also try to just email miran as he's been doing a lot of doc updating.

**Comment by c-blake** [comment]
Oh, and https://nim-lang.org/docs/nimc.html#compiler-usage-search-path-handling is a bona fide link you can just click if that helps.

**Comment by pb-cdunn** [comment]
Oh! In the *compiler* manual. Of course! Thanks.

**Comment by c-blake** [comment]
You're welcome.  There really should be at least a _pointer_ to that section of the compiler manual from the language manual somewhere around "Collective imports".  That is also talking about subdir structure of to-be-imported stuff.

**Pull request closed without merging**
